In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Vocabulary size
voc_size=10000

# One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6983, 8767, 995, 9101], [6983, 8767, 995, 4621], [6983, 3958, 995, 4398], [482, 8579, 6331, 8389, 382], [482, 8579, 6331, 8389, 8915], [8331, 6983, 5195, 995, 3440], [8300, 1080, 2873, 8389]]


# Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6983 8767  995 9101]
 [   0    0    0    0 6983 8767  995 4621]
 [   0    0    0    0 6983 3958  995 4398]
 [   0    0    0  482 8579 6331 8389  382]
 [   0    0    0  482 8579 6331 8389 8915]
 [   0    0    0 8331 6983 5195  995 3440]
 [   0    0    0    0 8300 1080 2873 8389]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 248ms/step
[[[-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046
   -0.00276117  0.01424647 -0.00578636 -0.01374988  0.00676429]
  [-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046
   -0.00276117  0.01424647 -0.00578636 -0.01374988  0.00676429]
  [-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046
   -0.00276117  0.01424647 -0.00578636 -0.01374988  0.00676429]
  [-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046
   -0.00276117  0.01424647 -0.00578636 -0.01374988  0.00676429]
  [-0.02503748 -0.01773538  0.02567715  0.01547872  0.02414532
    0.03603278 -0.03715634 -0.00205261  0.00340784 -0.04185127]
  [ 0.03360181  0.00680072  0.02208826 -0.04494342  0.02796059
    0.03332124 -0.0084326   0.04781563  0.00100695 -0.02144084]
  [-0.00089671  0.03018366 -0.04927914 -0.00657177  0.02937331
    0.03456305 -0.01907619 -0.02054249 -0.04908195  0.03313979]
  [-0.01905695 -0.0314356   0.00110894 -0.02289747  0.0158

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 6983, 8767,  995, 9101])

In [14]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 25ms/step
[[-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046 -0.00276117
   0.01424647 -0.00578636 -0.01374988  0.00676429]
 [-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046 -0.00276117
   0.01424647 -0.00578636 -0.01374988  0.00676429]
 [-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046 -0.00276117
   0.01424647 -0.00578636 -0.01374988  0.00676429]
 [-0.04757006 -0.01055019 -0.03497471  0.02511393  0.00502046 -0.00276117
   0.01424647 -0.00578636 -0.01374988  0.00676429]
 [-0.02503748 -0.01773538  0.02567715  0.01547872  0.02414532  0.03603278
  -0.03715634 -0.00205261  0.00340784 -0.04185127]
 [ 0.03360181  0.00680072  0.02208826 -0.04494342  0.02796059  0.03332124
  -0.0084326   0.04781563  0.00100695 -0.02144084]
 [-0.00089671  0.03018366 -0.04927914 -0.00657177  0.02937331  0.03456305
  -0.01907619 -0.02054249 -0.04908195  0.03313979]
 [-0.01905695 -0.0314356   0.00110894 -0.02289747  0.0158737   0.04706224